server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # msk 설정
    # properties:
    #   security.protocol: SASL_SSL
    #   sasl.mechanism: AWS_MSK_IAM
    #   sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
    #   sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
    
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      # elastiCache 설정
      # ssl:
      #   enabled: true

client:
  user-service:
    url: ${USER_SERVICE_URL}
  point-service:
    url: ${POINT_SERVICE_URL}

logging:
  level:
    org.springframework.cache: trace