services:
  board-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/board-service:latest
    restart: unless-stopped
    ports:
      - "8080"
    env_file:
      - .env
    # environment:
    #   SERVER_PORT: ${SERVER_PORT}
    #   SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    #   SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    #   SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    #   SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    #   SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
    #   SPRING_DATA_REDIS_PORT: ${REDIS_PORT}

    #   # SPRING_DATA_REDIS_CLUSTER_NODE: ${ELASTI_CACHE_NODE}

    #   USER_SERVICE_URL: ${USER_SERVICE_URL}
    #   POINT_SERVICE_URL: ${POINT_SERVICE_URL}